//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HRLK7A2F\\MSSQLSERVER01;Initial Catalog=recruitment;Integrated " +
            "Security=True;TrustServerCertificate=True")]
        public string recruitmentConnectionString {
            get {
                return ((string)(this["recruitmentConnectionString"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BESHIR\\SQLEXPRESS;Initial Catalog=recruitment;Integrated Security=Tru" +
            "e;Encrypt=True;TrustServerCertificate=True")]
        public string recruitment {
            get {
                return ((string)(this["recruitment"]));
>>>>>>> 0913a797b0cfa2e992a6b5c729258e2bfe679ba4
            }
        }
    }
}
